### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by sionedgo** [freemasonrycc/blockchain#25]
### Summary
Currently we use comet's interface for logging in the sdk. While this is an okay solution, zero log and other loggers have the opportunity to be typed. Secondly, the comet logger is limiting in what we would like to achieve with logging. For now, we have recreated the same interface to not cause large breaking changes, but once the sdk is migrated to the new interface and its loggers, we should break the interface, remove comet as a dependency and define the interface as we want.
### Work Breakdown

 

- [ ] lntroduce logger interface same as comets
- [ ] Introduce noplogger and migrate the repo to use it.
- [ ] Introduce zero logger and migrate the repo to use it
- [ ] Add Filtering to zerolog
- [ ] Break the logger interface to remove comet dep and better fit our needs
- [ ] Create a wrapper logger that can be passed to comet on start.

**Comment by fedekunz** [comment]
with reason
